### ISSUE TITLE
Injector injects into water

### ISSUE THREAD

**Issue by BalintXHD** [Akrivus/Amalgam#6] opened 2018-12-10 18:14 UTC
![2018-12-10_19 13 37](https://user-images.githubusercontent.com/36235183/49752139-c5a1ed00-fcaf-11e8-8fb6-df7b51e6df38.png)

**Comment by Akrivus** [comment] 2018-12-10 18:17
Duplicate of #2

**Closed by Akrivus** 2018-12-10 18:17 UTC
